# Site settings
title:          Max Chiswick
description:    ""
baseurl:        ""
url:            "https://chisness.github.io"

# Google Analytics
google_analytics: UA-20826585-3

# Author
author:
  name:         Max Chiswick
  url:          https://maxchiswick.com
  email:        max.chiswick@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
